### ISSUE TITLE
Installation problems in Ubuntu while building from source

### ISSUE THREAD

**Issue by kvmanohar22** [IntelVCL/Open3D#400]
Setup details: `Ubuntu 18.04 LTS`
```
$ uname -a
Linux user 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
I'm building from source. Having installed all the dependencies, the following linker error still seems to pop-up.

```
[  1%] Built target EncodeShader
[  2%] Built target ShaderFileTarget
[ 24%] Built target Visualization
[ 26%] Built target tinyfiledialogs
[ 53%] Built target Core
[ 69%] Built target IO
[ 69%] Built target Open3D
[ 70%] Built target ConvertPointCloud
[ 71%] Built target MergeMesh
[ 73%] Linking CXX executable ../bin/ManuallyCropPointCloud
/usr/bin/x86_64-linux-gnu-ld: /usr/local/lib/libglfw3.a(vulkan.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Experimental/CMakeFiles/ViewPCDMatch.dir/build.make:98: recipe for target 'bin/Experimental/ViewPCDMatch' failed
make[2]: *** [bin/Experimental/ViewPCDMatch] Error 1
CMakeFiles/Makefile2:603: recipe for target 'Experimental/CMakeFiles/ViewPCDMatch.dir/all' failed
make[1]: *** [Experimental/CMakeFiles/ViewPCDMatch.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

The error doesn't seem to vanish even after manually adding the line `list(APPEND DEPENDENCIES "/lib/x86_64-linux-gnu/libdl.so.2")` to the dependencies in the file `Open3D/src/Tools/CMakeLists.txt` for the target `ManuallyCropPointCloud`

I don't understand what else I could be missing.
Any help would be greatly appreciated.

**Comment by takanokage** [comment]
I just submitted a PR about docker for open3d.
I was able to successfully build on Ubuntu 18.04. Maybe you can find some
inspiration there.

**Comment by kvmanohar22** [comment]
Sounds great! Waiting for the PR to get merged

**Comment by kvmanohar22** [comment]
@takanokage Thanks a lot! 
I was able to successfully install Open3D!!

**Comment by takanokage** [comment]
awesome, I'm glad it worked!
